export default {
  state: {
    events: [
      {
        _id: '1',
        name: 'Project Management Lecture',
        location: 'room N117',
        date: '2019-10-23',
        time: '2:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '2',
        name: 'Project Management Laboratory',
        location: 'room N533',
        date: '2019-10-23',
        time: '3:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '3',
        name: 'Project Management Lecture',
        location: 'room N117',
        date: '2019-10-23',
        time: '2:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '4',
        name: 'Project Management Laboratory',
        location: 'room N533',
        date: '2019-10-23',
        time: '3:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '5',
        name: 'Project Management Lecture',
        location: 'room N117',
        date: '2019-10-23',
        time: '2:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '6',
        name: 'Project Management Laboratory',
        location: 'room N533',
        date: '2019-10-23',
        time: '3:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '7',
        name: 'Project Management Lecture',
        location: 'room N117',
        date: '2019-10-23',
        time: '2:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '8',
        name: 'Project Management Laboratory',
        location: 'room N533',
        date: '2019-10-23',
        time: '3:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '9',
        name: 'Project Management Lecture',
        location: 'room N117',
        date: '2019-10-23',
        time: '2:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
      {
        _id: '10',
        name: 'Project Management Laboratory',
        location: 'room N533',
        date: '2019-10-23',
        time: '3:00',
        end_date: '2019-10-23',
        end_time: '3:00',
        staff: 'Tiffany Young',
        tasks: 'Client Meeting',
        notes: '',
      },
    ],
  },
  getters: {
    getEvents: state => {
      return state.events;
    },
  },
};
